name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show folder structure (debug)
      run: pwd && ls -R

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      working-directory: automationexercise
      run: mvn -B clean install -DskipTests

    - name: Run Tests
      working-directory: automationexercise
      run: mvn test

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: automationexercise/target/surefire-reports

    - name: Show test log output
      if: failure()
      run: cat automationexercise/target/surefire-reports/*.txt || true


    - name: Set up Chrome for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &


      
